name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make
      shell: powershell

    - name: Build
      run: make

    - name: Run program
      run: ./main   # change if your binary has another name
